// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file todo.proto (package todo.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file todo.proto.
 */
export const file_todo: GenFile = /*@__PURE__*/
  fileDesc("Cgp0b2RvLnByb3RvEgd0b2RvLnYxIjQKBFRvZG8SCgoCaWQYASABKAkSDQoFdGl0bGUYAiABKAkSEQoJY29tcGxldGVkGAMgASgIIiIKEUNyZWF0ZVRvZG9SZXF1ZXN0Eg0KBXRpdGxlGAEgASgJIjEKEkNyZWF0ZVRvZG9SZXNwb25zZRIbCgR0b2RvGAEgASgLMg0udG9kby52MS5Ub2RvIhIKEExpc3RUb2Rvc1JlcXVlc3QiMQoRTGlzdFRvZG9zUmVzcG9uc2USHAoFdG9kb3MYASADKAsyDS50b2RvLnYxLlRvZG8iHwoRRGVsZXRlVG9kb1JlcXVlc3QSCgoCaWQYASABKAkiJQoSRGVsZXRlVG9kb1Jlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgy3wEKC1RvZG9TZXJ2aWNlEkUKCkNyZWF0ZVRvZG8SGi50b2RvLnYxLkNyZWF0ZVRvZG9SZXF1ZXN0GhsudG9kby52MS5DcmVhdGVUb2RvUmVzcG9uc2USQgoJTGlzdFRvZG9zEhkudG9kby52MS5MaXN0VG9kb3NSZXF1ZXN0GhoudG9kby52MS5MaXN0VG9kb3NSZXNwb25zZRJFCgpEZWxldGVUb2RvEhoudG9kby52MS5EZWxldGVUb2RvUmVxdWVzdBobLnRvZG8udjEuRGVsZXRlVG9kb1Jlc3BvbnNlQiFaH3RvZG8tYmFja2VuZC9nZW4vdG9kby92MTt0b2RvdjFiBnByb3RvMw");

/**
 * @generated from message todo.v1.Todo
 */
export type Todo = Message<"todo.v1.Todo"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: bool completed = 3;
   */
  completed: boolean;
};

/**
 * Describes the message todo.v1.Todo.
 * Use `create(TodoSchema)` to create a new message.
 */
export const TodoSchema: GenMessage<Todo> = /*@__PURE__*/
  messageDesc(file_todo, 0);

/**
 * @generated from message todo.v1.CreateTodoRequest
 */
export type CreateTodoRequest = Message<"todo.v1.CreateTodoRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;
};

/**
 * Describes the message todo.v1.CreateTodoRequest.
 * Use `create(CreateTodoRequestSchema)` to create a new message.
 */
export const CreateTodoRequestSchema: GenMessage<CreateTodoRequest> = /*@__PURE__*/
  messageDesc(file_todo, 1);

/**
 * @generated from message todo.v1.CreateTodoResponse
 */
export type CreateTodoResponse = Message<"todo.v1.CreateTodoResponse"> & {
  /**
   * @generated from field: todo.v1.Todo todo = 1;
   */
  todo?: Todo;
};

/**
 * Describes the message todo.v1.CreateTodoResponse.
 * Use `create(CreateTodoResponseSchema)` to create a new message.
 */
export const CreateTodoResponseSchema: GenMessage<CreateTodoResponse> = /*@__PURE__*/
  messageDesc(file_todo, 2);

/**
 * @generated from message todo.v1.ListTodosRequest
 */
export type ListTodosRequest = Message<"todo.v1.ListTodosRequest"> & {
};

/**
 * Describes the message todo.v1.ListTodosRequest.
 * Use `create(ListTodosRequestSchema)` to create a new message.
 */
export const ListTodosRequestSchema: GenMessage<ListTodosRequest> = /*@__PURE__*/
  messageDesc(file_todo, 3);

/**
 * @generated from message todo.v1.ListTodosResponse
 */
export type ListTodosResponse = Message<"todo.v1.ListTodosResponse"> & {
  /**
   * @generated from field: repeated todo.v1.Todo todos = 1;
   */
  todos: Todo[];
};

/**
 * Describes the message todo.v1.ListTodosResponse.
 * Use `create(ListTodosResponseSchema)` to create a new message.
 */
export const ListTodosResponseSchema: GenMessage<ListTodosResponse> = /*@__PURE__*/
  messageDesc(file_todo, 4);

/**
 * @generated from message todo.v1.DeleteTodoRequest
 */
export type DeleteTodoRequest = Message<"todo.v1.DeleteTodoRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message todo.v1.DeleteTodoRequest.
 * Use `create(DeleteTodoRequestSchema)` to create a new message.
 */
export const DeleteTodoRequestSchema: GenMessage<DeleteTodoRequest> = /*@__PURE__*/
  messageDesc(file_todo, 5);

/**
 * @generated from message todo.v1.DeleteTodoResponse
 */
export type DeleteTodoResponse = Message<"todo.v1.DeleteTodoResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message todo.v1.DeleteTodoResponse.
 * Use `create(DeleteTodoResponseSchema)` to create a new message.
 */
export const DeleteTodoResponseSchema: GenMessage<DeleteTodoResponse> = /*@__PURE__*/
  messageDesc(file_todo, 6);

/**
 * @generated from service todo.v1.TodoService
 */
export const TodoService: GenService<{
  /**
   * @generated from rpc todo.v1.TodoService.CreateTodo
   */
  createTodo: {
    methodKind: "unary";
    input: typeof CreateTodoRequestSchema;
    output: typeof CreateTodoResponseSchema;
  },
  /**
   * @generated from rpc todo.v1.TodoService.ListTodos
   */
  listTodos: {
    methodKind: "unary";
    input: typeof ListTodosRequestSchema;
    output: typeof ListTodosResponseSchema;
  },
  /**
   * @generated from rpc todo.v1.TodoService.DeleteTodo
   */
  deleteTodo: {
    methodKind: "unary";
    input: typeof DeleteTodoRequestSchema;
    output: typeof DeleteTodoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_todo, 0);

